### ISSUE TITLE
UI to set password for account private key unlocking

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/substrate-connect#1837]
```[tasklist]
### Tasks
- [x] encrypt keystore with password (implemented in #1960)
- [x] encrypt keyset seed (depends on #1965)
- [x] encrypt account private keys (depends on #1965)
```
