### ISSUE TITLE
Scaffold Basic Extension UI and RPC to submit a transaction

### ISSUE THREAD

**Issue by kratico** [paritytech/substrate-connect#1894]
```[tasklist]
### Tasks
- [x] fetch selected account balance
- [x] handle form fields and submission with react
- [x] fetch accounts from extension
- [ ] validate destination address
- [x] use PAPI to encode the transaction calldata
- [x] transfer should trigger an extension popup that signs the transaction
- [x] extract transaction submission into a hook
- [x] follow transaction submission events until it is finalized
- [x] share observable client across hooks/components
- [ ] https://github.com/paritytech/substrate-connect/pull/1914
- [ ] add block number
- [ ] transaction hash
- [ ] switch between chains
- [ ] add transaction fee
```
