### ISSUE TITLE
Account management

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/substrate-connect#1932]
```[tasklist]
### Tasks
- [x] UI to create seed phrase
- [ ] https://github.com/paritytech/substrate-connect/issues/1933
- [x] UI to select the enabled chains for the Account
- [x] Storage for seed, signature scheme, derivation paths, account names (+ other data)
- [x] Storage for mapping between accounts and Chains
- [x] Extension UI to manage accounts
- [x] Extension UI to manage account enabled chains
- [ ] PolkadotProvider implement spec chain.getAccounts()
- [ ] PolkadotProvider implement spec chain.onAccountsChange()
- [ ] Internal RPC spec and background implementation for all the above
- [x] UI to create seed phrase
```
