### ISSUE TITLE
Data Signing

### ISSUE THREAD

**Issue by kratico** [paritytech/substrate-connect#1990]
```[tasklist]
### Tasks
- [ ] Implement new Polkadot Provider Signer API
- [x] UI to prompt the user to approve data signing
- [x] Internal RPC spec and background implementation for all the above
```
