### ISSUE TITLE
Transaction Review and Approval

### ISSUE THREAD

**Issue by kratico** [paritytech/substrate-connect#1991]
```[tasklist]
### Tasks
- [ ] ~~PolkadotProvider implement spec `JsonProvider.createTx(from, callData)`~~
- [x] UI to unlock the needed account private key for signing
- [x] UI to prompt the user to review, approve and submit the extrinsic
- [x] Component to show the decoded call
- [x] Component to prompt chain signed extensions user inputs (for example: fees, mortality, etc.)
- [x] ~UI or Popup to follow the extrinsic submission events or status~ (should be done by the DApp)
- [x] Internal RPC spec and background implementation for all the above
```
