### ISSUE TITLE
Multi Injected Provider Discoverability (similar to EIP-6964)

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/substrate-connect#2052]
```[tasklist]
### Tasks
- [x] UI (DApp) to present available providers
- [x] UI (DApp) to select/switch an available provider
- [ ] https://github.com/paritytech/substrate-connect/issues/2136
```

**Comment by ryanleecode** [comment]
remaing work is to update to new polkadot provider spec
