### ISSUE TITLE
[MS] Substrate Connect Next Task List

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/substrate-connect#2058]
```[tasklist]
### ~~Implement Polkadot Provider API.~~ Superseded by @substrate/discovery
- [ ] ~~Replace UnstableProvider with a implementation of the new Polkadot Provider API~~
- [ ] ~~Document the Polkadot Provider spec: https://github.com/paritytech/polkadot-provider~~
```

```[tasklist]
### Create/Sign transactions without using centralized RPC nodes.
- [ ] https://github.com/paritytech/substrate-connect/pull/1886
```

```[tasklist]
### Support discovering multiple injected Polkadot Wallet Providers.
- [ ] https://github.com/paritytech/substrate-connect/issues/2052
- [ ] https://github.com/paritytech/substrate-connect/issues/2182
```

```[tasklist]
### Account Management
- [ ] https://github.com/paritytech/substrate-connect/issues/2040
- [ ] https://github.com/paritytech/substrate-connect/issues/1933
- [x] https://github.com/paritytech/substrate-connect/pull/1965
- [x] https://github.com/paritytech/substrate-connect/pull/2010
- [ ] https://github.com/paritytech/substrate-connect/issues/2117
- [ ] PolkadotProvider implement spec chain.getAccounts()
- [ ] PolkadotProvider implement spec chain.onAccountsChange()
- [ ] Export Accounts
```

```[tasklist]
### Chain Management
- [ ] https://github.com/paritytech/substrate-connect/issues/2054
- [ ] https://github.com/paritytech/substrate-connect/issues/2123
- [x] https://github.com/paritytech/substrate-connect/issues/2147
- [ ] https://github.com/paritytech/substrate-connect/issues/2135
- [ ] https://github.com/paritytech/substrate-connect/issues/2053
- [ ] correlate list of parachains to their associated relay chain
```

```[tasklist]
### Transaction review/approval/signing
- [ ] https://github.com/paritytech/substrate-connect/pull/1924
- [ ] https://github.com/paritytech/substrate-connect/pull/1914
- [ ] https://github.com/paritytech/substrate-connect/pull/1904
- [ ] https://github.com/paritytech/substrate-connect/issues/1990
```

```[tasklist]
### Misc
- [ ] https://github.com/paritytech/substrate-connect/issues/2057
- [ ] https://github.com/paritytech/substrate-connect/issues/2059
- [ ] https://github.com/paritytech/substrate-connect/issues/2055
- [ ] https://github.com/paritytech/substrate-connect/pull/1995
- [ ] https://github.com/paritytech/substrate-connect/issues/2109
- [ ] https://github.com/paritytech/substrate-connect/issues/1786
- [ ] #2183 
```

## Nice to Haves

```[tasklist]
### Polkadot Vault Integration
```
