### ISSUE TITLE
Support unknown Chainspecs (e.g. parachains)

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#361]
This is created as an umbrella ticket for adding in substrate-connect the functionality of supporting external chainspecs after consent of user (e.g. Parachains support).

In addition this will give extra functionality on substrate connect extension to keep a map of chainspecs/app approved from user in the local storage.

Following [Figma](https://www.figma.com/file/iBXxXdzoLgmNS3i0ZMOee5/Flows?node-id=0%3A1) screenshot shows a flowchart  of the approval process:

![Screenshot from 2021-06-22 12-20-58](https://user-images.githubusercontent.com/5408605/122915731-bf068d00-d364-11eb-8e7b-8de705b6c0ea.png)

Related isses:

- [x] Create localstorage map for new apps/chainspecs #357 
- [ ] Permission dialogue (trust check) for new, unknown incoming apps #358 
- [ ] Alter Extension's option page #359
- [x] Update Extension designs #360

**Comment by tomaka** [comment]
Everything is done here.
