### ISSUE TITLE
Background page and SmoldotClientManager

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/substrate-connect#94]
## Tasks
* [x] Upstream the typescript typings to smoldot
* [x] Extract the smoldot client test helpers into a separate package
* [x] Implement request and subscription proxying
* [x] Capture the tabId and URL when a Uapp connects
* [x] Implement loading and saving database
* [x] Add AppMediator tests
* [x] Add ConnectionManager tests
* [x] Clean up subscriptions on disconnect

#### What should the SmoldotClientManager do

The `SmoldotClientManager` inside the extension must broker RPC requests and responses from multiple clients residing on browser pages (aka content pages) to multiple smoldot blockchain clients in the extension (for now we have one but there will be many).   This entails:
* The `SmoldotProvider` in each webpage will issue RPC requests with ids in its own namespace (starting from 1). The `SmoldotClientManager` must maintain a translation table of client request ids to the actual request ids and send the correct responses to the correct clients. The translation table will be a map of clients to ID mappings where an ID mapping is the originating request id and the actual request id sent to smoldot. The `SmoldotClientManager` will change the request and response IDs in the JSON on the fly and maintain the list of live mappings.
  * Remove the ID mapping when the response has been received for non-subscriptions
  * Remove the ID mapping when an  unsubscribe request / response has happened
  * Remove all mappings when a page disconnects from the extension
* The `SmoldotClientManager` must detect when clients disconnect and send unsubscribe messages for all that clients' subscriptions.
* The `SmoldotClientManager` could also intelligently cache queries in the future (out of scope for now).

**Comment by raoulmillais** [comment]
Upstream PR for typings in smoldot is here: https://github.com/paritytech/smoldot/pull/495
