### ISSUE TITLE
Umbrella issue - Refactor Extension UI

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#975]
Tasks for refactor are:

- [ ] Alter configuration to remove Material-ui (deprecated version) and use tailwindCss, mottled-library, postcss instead (recreate existing design)

### Refactor Popup Page UI
- [ ] Adjust UI to to aadapt to [figma](https://www.figma.com/file/s8KFS3Anf7Wfk2axp8UdUY/Substrate-Connect-Extension-01?node-id=35%3A520) files
- [ ] Fix "network is disconnected" functionality (that will be done for now when `peers = 0` - showing the reason.

### Refactor Popup Page UI
- [ ] Refactor Options Page UI to adjust to [figma](https://www.figma.com/file/s8KFS3Anf7Wfk2axp8UdUY/Substrate-Connect-Extension-01?node-id=35%3A520) files
- [ ] Add bootnodes functionality API and save in extension localstorage
